# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: activity/v1alpha/activity.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'activity/v1alpha/activity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61\x63tivity/v1alpha/activity.proto\x12\x19\x63om.seed.activity.v1alpha\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n\x11ListEventsRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\x12\x14\n\x0ctrusted_only\x18\x03 \x01(\x08\x12\x16\n\x0e\x66ilter_authors\x18\x04 \x03(\t\x12\x19\n\x11\x66ilter_event_type\x18\x05 \x03(\t\x12\x17\n\x0f\x66ilter_resource\x18\x06 \x01(\t\x12\x1b\n\x13\x61\x64\x64_linked_resource\x18\x07 \x03(\t\"_\n\x12ListEventsResponse\x12\x30\n\x06\x65vents\x18\x01 \x03(\x0b\x32 .com.seed.activity.v1alpha.Event\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"\xbf\x01\n\x05\x45vent\x12;\n\x08new_blob\x18\x01 \x01(\x0b\x32\'.com.seed.activity.v1alpha.NewBlobEventH\x00\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12.\n\nevent_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0cobserve_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x06\n\x04\x64\x61ta\"e\n\x0cNewBlobEvent\x12\x0b\n\x03\x63id\x18\x01 \x01(\t\x12\x11\n\tblob_type\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x10\n\x08resource\x18\x04 \x01(\t\x12\x13\n\x0b\x65xtra_attrs\x18\x05 \x01(\t2y\n\x0c\x41\x63tivityFeed\x12i\n\nListEvents\x12,.com.seed.activity.v1alpha.ListEventsRequest\x1a-.com.seed.activity.v1alpha.ListEventsResponseB1Z/seed/backend/genproto/activity/v1alpha;activityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'activity.v1alpha.activity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/seed/backend/genproto/activity/v1alpha;activity'
  _globals['_LISTEVENTSREQUEST']._serialized_start=96
  _globals['_LISTEVENTSREQUEST']._serialized_end=281
  _globals['_LISTEVENTSRESPONSE']._serialized_start=283
  _globals['_LISTEVENTSRESPONSE']._serialized_end=378
  _globals['_EVENT']._serialized_start=381
  _globals['_EVENT']._serialized_end=572
  _globals['_NEWBLOBEVENT']._serialized_start=574
  _globals['_NEWBLOBEVENT']._serialized_end=675
  _globals['_ACTIVITYFEED']._serialized_start=677
  _globals['_ACTIVITYFEED']._serialized_end=798
# @@protoc_insertion_point(module_scope)
