# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: activity/v1alpha/subscriptions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'activity/v1alpha/subscriptions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$activity/v1alpha/subscriptions.proto\x12\x19\x63om.seed.activity.v1alpha\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"b\n\x10SubscribeRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x11\n\trecursive\x18\x03 \x01(\x08\x12\x12\n\x05\x61sync\x18\x04 \x01(\x08H\x00\x88\x01\x01\x42\x08\n\x06_async\"3\n\x12UnsubscribeRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"A\n\x18ListSubscriptionsRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\"t\n\x19ListSubscriptionsResponse\x12>\n\rsubscriptions\x18\x01 \x03(\x0b\x32\'.com.seed.activity.v1alpha.Subscription\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"k\n\x0cSubscription\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x11\n\trecursive\x18\x03 \x01(\x08\x12)\n\x05since\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xb7\x02\n\rSubscriptions\x12P\n\tSubscribe\x12+.com.seed.activity.v1alpha.SubscribeRequest\x1a\x16.google.protobuf.Empty\x12T\n\x0bUnsubscribe\x12-.com.seed.activity.v1alpha.UnsubscribeRequest\x1a\x16.google.protobuf.Empty\x12~\n\x11ListSubscriptions\x12\x33.com.seed.activity.v1alpha.ListSubscriptionsRequest\x1a\x34.com.seed.activity.v1alpha.ListSubscriptionsResponseB1Z/seed/backend/genproto/activity/v1alpha;activityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'activity.v1alpha.subscriptions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/seed/backend/genproto/activity/v1alpha;activity'
  _globals['_SUBSCRIBEREQUEST']._serialized_start=129
  _globals['_SUBSCRIBEREQUEST']._serialized_end=227
  _globals['_UNSUBSCRIBEREQUEST']._serialized_start=229
  _globals['_UNSUBSCRIBEREQUEST']._serialized_end=280
  _globals['_LISTSUBSCRIPTIONSREQUEST']._serialized_start=282
  _globals['_LISTSUBSCRIPTIONSREQUEST']._serialized_end=347
  _globals['_LISTSUBSCRIPTIONSRESPONSE']._serialized_start=349
  _globals['_LISTSUBSCRIPTIONSRESPONSE']._serialized_end=465
  _globals['_SUBSCRIPTION']._serialized_start=467
  _globals['_SUBSCRIPTION']._serialized_end=574
  _globals['_SUBSCRIPTIONS']._serialized_start=577
  _globals['_SUBSCRIPTIONS']._serialized_end=888
# @@protoc_insertion_point(module_scope)
