# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import daemon_pb2 as daemon__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DaemonStub(object):
    """Daemon API encapsulates main functionality of the Mintter daemon.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenMnemonic = channel.unary_unary(
                '/com.mintter.daemon.v1alpha.Daemon/GenMnemonic',
                request_serializer=daemon__pb2.GenMnemonicRequest.SerializeToString,
                response_deserializer=daemon__pb2.GenMnemonicResponse.FromString,
                )
        self.Register = channel.unary_unary(
                '/com.mintter.daemon.v1alpha.Daemon/Register',
                request_serializer=daemon__pb2.RegisterRequest.SerializeToString,
                response_deserializer=daemon__pb2.RegisterResponse.FromString,
                )
        self.GetInfo = channel.unary_unary(
                '/com.mintter.daemon.v1alpha.Daemon/GetInfo',
                request_serializer=daemon__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=daemon__pb2.Info.FromString,
                )
        self.ForceSync = channel.unary_unary(
                '/com.mintter.daemon.v1alpha.Daemon/ForceSync',
                request_serializer=daemon__pb2.ForceSyncRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class DaemonServicer(object):
    """Daemon API encapsulates main functionality of the Mintter daemon.
    """

    def GenMnemonic(self, request, context):
        """Generates a set of mnemonics words used to derive Mintter Account Key, and the underlying 
        mintter lndhub wallet. The cipher schema is BIP-39 and the entropy is encoded as a 
        mnemonic of 12-24 human-readable english words.
        The seed could be reconstructed given these words and the passphrase.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """After generating the seed, this call is used to commit the seed and
        create an account binding between the device and account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfo(self, request, context):
        """Get generic information about the running node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceSync(self, request, context):
        """Force-trigger periodic background sync of Mintter objects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenMnemonic': grpc.unary_unary_rpc_method_handler(
                    servicer.GenMnemonic,
                    request_deserializer=daemon__pb2.GenMnemonicRequest.FromString,
                    response_serializer=daemon__pb2.GenMnemonicResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=daemon__pb2.RegisterRequest.FromString,
                    response_serializer=daemon__pb2.RegisterResponse.SerializeToString,
            ),
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=daemon__pb2.GetInfoRequest.FromString,
                    response_serializer=daemon__pb2.Info.SerializeToString,
            ),
            'ForceSync': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceSync,
                    request_deserializer=daemon__pb2.ForceSyncRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.mintter.daemon.v1alpha.Daemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Daemon(object):
    """Daemon API encapsulates main functionality of the Mintter daemon.
    """

    @staticmethod
    def GenMnemonic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mintter.daemon.v1alpha.Daemon/GenMnemonic',
            daemon__pb2.GenMnemonicRequest.SerializeToString,
            daemon__pb2.GenMnemonicResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mintter.daemon.v1alpha.Daemon/Register',
            daemon__pb2.RegisterRequest.SerializeToString,
            daemon__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mintter.daemon.v1alpha.Daemon/GetInfo',
            daemon__pb2.GetInfoRequest.SerializeToString,
            daemon__pb2.Info.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ForceSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.mintter.daemon.v1alpha.Daemon/ForceSync',
            daemon__pb2.ForceSyncRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
