# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from documents.v3alpha import resources_pb2 as documents_dot_v3alpha_dot_resources__pb2
from p2p.v1alpha import syncing_pb2 as p2p_dot_v1alpha_dot_syncing__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in documents/v3alpha/resources_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResourcesStub(object):
    """Service for querying Hypermedia resources.

    Note: This API had to be separate to avoid circular dependencies between documents and comments.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetResource = channel.unary_unary(
                '/com.seed.documents.v3alpha.Resources/GetResource',
                request_serializer=documents_dot_v3alpha_dot_resources__pb2.GetResourceRequest.SerializeToString,
                response_deserializer=documents_dot_v3alpha_dot_resources__pb2.Resource.FromString,
                _registered_method=True)
        self.PushResourcesToPeer = channel.unary_stream(
                '/com.seed.documents.v3alpha.Resources/PushResourcesToPeer',
                request_serializer=documents_dot_v3alpha_dot_resources__pb2.PushResourcesToPeerRequest.SerializeToString,
                response_deserializer=p2p_dot_v1alpha_dot_syncing__pb2.AnnounceBlobsProgress.FromString,
                _registered_method=True)


class ResourcesServicer(object):
    """Service for querying Hypermedia resources.

    Note: This API had to be separate to avoid circular dependencies between documents and comments.
    """

    def GetResource(self, request, context):
        """Gets a single resource with a URL (technically IRI).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushResourcesToPeer(self, request, context):
        """Makes sure a resource (and their related blobs) are pushed to a given peer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResourcesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetResource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResource,
                    request_deserializer=documents_dot_v3alpha_dot_resources__pb2.GetResourceRequest.FromString,
                    response_serializer=documents_dot_v3alpha_dot_resources__pb2.Resource.SerializeToString,
            ),
            'PushResourcesToPeer': grpc.unary_stream_rpc_method_handler(
                    servicer.PushResourcesToPeer,
                    request_deserializer=documents_dot_v3alpha_dot_resources__pb2.PushResourcesToPeerRequest.FromString,
                    response_serializer=p2p_dot_v1alpha_dot_syncing__pb2.AnnounceBlobsProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.seed.documents.v3alpha.Resources', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.seed.documents.v3alpha.Resources', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Resources(object):
    """Service for querying Hypermedia resources.

    Note: This API had to be separate to avoid circular dependencies between documents and comments.
    """

    @staticmethod
    def GetResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.seed.documents.v3alpha.Resources/GetResource',
            documents_dot_v3alpha_dot_resources__pb2.GetResourceRequest.SerializeToString,
            documents_dot_v3alpha_dot_resources__pb2.Resource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushResourcesToPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.seed.documents.v3alpha.Resources/PushResourcesToPeer',
            documents_dot_v3alpha_dot_resources__pb2.PushResourcesToPeerRequest.SerializeToString,
            p2p_dot_v1alpha_dot_syncing__pb2.AnnounceBlobsProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
