# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: documents/v3alpha/resources.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'documents/v3alpha/resources.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from documents.v3alpha import documents_pb2 as documents_dot_v3alpha_dot_documents__pb2
from documents.v3alpha import comments_pb2 as documents_dot_v3alpha_dot_comments__pb2
from p2p.v1alpha import syncing_pb2 as p2p_dot_v1alpha_dot_syncing__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!documents/v3alpha/resources.proto\x12\x1a\x63om.seed.documents.v3alpha\x1a!documents/v3alpha/documents.proto\x1a documents/v3alpha/comments.proto\x1a\x19p2p/v1alpha/syncing.proto\"!\n\x12GetResourceRequest\x12\x0b\n\x03iri\x18\x01 \x01(\t\"\xcd\x01\n\x08Resource\x12\x38\n\x08\x64ocument\x18\x01 \x01(\x0b\x32$.com.seed.documents.v3alpha.DocumentH\x00\x12\x36\n\x07\x63omment\x18\x02 \x01(\x0b\x32#.com.seed.documents.v3alpha.CommentH\x00\x12\x36\n\x07\x63ontact\x18\x03 \x01(\x0b\x32#.com.seed.documents.v3alpha.ContactH\x00\x12\x0f\n\x07version\x18\x04 \x01(\tB\x06\n\x04kind\">\n\x1aPushResourcesToPeerRequest\x12\r\n\x05\x61\x64\x64rs\x18\x01 \x03(\t\x12\x11\n\tresources\x18\x02 \x03(\t2\xee\x01\n\tResources\x12\x63\n\x0bGetResource\x12..com.seed.documents.v3alpha.GetResourceRequest\x1a$.com.seed.documents.v3alpha.Resource\x12|\n\x13PushResourcesToPeer\x12\x36.com.seed.documents.v3alpha.PushResourcesToPeerRequest\x1a+.com.seed.p2p.v1alpha.AnnounceBlobsProgress0\x01\x42\x33Z1seed/backend/genproto/documents/v3alpha;documentsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'documents.v3alpha.resources_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1seed/backend/genproto/documents/v3alpha;documents'
  _globals['_GETRESOURCEREQUEST']._serialized_start=161
  _globals['_GETRESOURCEREQUEST']._serialized_end=194
  _globals['_RESOURCE']._serialized_start=197
  _globals['_RESOURCE']._serialized_end=402
  _globals['_PUSHRESOURCESTOPEERREQUEST']._serialized_start=404
  _globals['_PUSHRESOURCESTOPEERREQUEST']._serialized_end=466
  _globals['_RESOURCES']._serialized_start=469
  _globals['_RESOURCES']._serialized_end=707
# @@protoc_insertion_point(module_scope)
