# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from documents.v1alpha import changes_pb2 as documents_dot_v1alpha_dot_changes__pb2


class ChangesStub(object):
    """Changes service provides information about the atomic version controlled changes of Seed objects.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChangeInfo = channel.unary_unary(
                '/com.seed.documents.v1alpha.Changes/GetChangeInfo',
                request_serializer=documents_dot_v1alpha_dot_changes__pb2.GetChangeInfoRequest.SerializeToString,
                response_deserializer=documents_dot_v1alpha_dot_changes__pb2.ChangeInfo.FromString,
                )
        self.ListChanges = channel.unary_unary(
                '/com.seed.documents.v1alpha.Changes/ListChanges',
                request_serializer=documents_dot_v1alpha_dot_changes__pb2.ListChangesRequest.SerializeToString,
                response_deserializer=documents_dot_v1alpha_dot_changes__pb2.ListChangesResponse.FromString,
                )


class ChangesServicer(object):
    """Changes service provides information about the atomic version controlled changes of Seed objects.
    """

    def GetChangeInfo(self, request, context):
        """Returns information about a single change.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChanges(self, request, context):
        """List changes of a given object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChangesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChangeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChangeInfo,
                    request_deserializer=documents_dot_v1alpha_dot_changes__pb2.GetChangeInfoRequest.FromString,
                    response_serializer=documents_dot_v1alpha_dot_changes__pb2.ChangeInfo.SerializeToString,
            ),
            'ListChanges': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChanges,
                    request_deserializer=documents_dot_v1alpha_dot_changes__pb2.ListChangesRequest.FromString,
                    response_serializer=documents_dot_v1alpha_dot_changes__pb2.ListChangesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.seed.documents.v1alpha.Changes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Changes(object):
    """Changes service provides information about the atomic version controlled changes of Seed objects.
    """

    @staticmethod
    def GetChangeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.seed.documents.v1alpha.Changes/GetChangeInfo',
            documents_dot_v1alpha_dot_changes__pb2.GetChangeInfoRequest.SerializeToString,
            documents_dot_v1alpha_dot_changes__pb2.ChangeInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.seed.documents.v1alpha.Changes/ListChanges',
            documents_dot_v1alpha_dot_changes__pb2.ListChangesRequest.SerializeToString,
            documents_dot_v1alpha_dot_changes__pb2.ListChangesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
