# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: documents/v1alpha/changes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64ocuments/v1alpha/changes.proto\x12\x1a\x63om.seed.documents.v1alpha\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n\x14GetChangeInfoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"P\n\x12ListChangesRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\"g\n\x13ListChangesResponse\x12\x37\n\x07\x63hanges\x18\x01 \x03(\x0b\x32&.com.seed.documents.v1alpha.ChangeInfo\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"x\n\nChangeInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12/\n\x0b\x63reate_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x65ps\x18\x05 \x03(\t2\xe4\x01\n\x07\x43hanges\x12i\n\rGetChangeInfo\x12\x30.com.seed.documents.v1alpha.GetChangeInfoRequest\x1a&.com.seed.documents.v1alpha.ChangeInfo\x12n\n\x0bListChanges\x12..com.seed.documents.v1alpha.ListChangesRequest\x1a/.com.seed.documents.v1alpha.ListChangesResponseB3Z1seed/backend/genproto/documents/v1alpha;documentsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'documents.v1alpha.changes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1seed/backend/genproto/documents/v1alpha;documents'
  _GETCHANGEINFOREQUEST._serialized_start=96
  _GETCHANGEINFOREQUEST._serialized_end=130
  _LISTCHANGESREQUEST._serialized_start=132
  _LISTCHANGESREQUEST._serialized_end=212
  _LISTCHANGESRESPONSE._serialized_start=214
  _LISTCHANGESRESPONSE._serialized_end=317
  _CHANGEINFO._serialized_start=319
  _CHANGEINFO._serialized_end=439
  _CHANGES._serialized_start=442
  _CHANGES._serialized_end=670
# @@protoc_insertion_point(module_scope)
