# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: documents/v1alpha/content_graph.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%documents/v1alpha/content_graph.proto\x12\x1a\x63om.seed.documents.v1alpha\"+\n\x14ListCitationsRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\"H\n\x15ListCitationsResponse\x12/\n\x05links\x18\x01 \x03(\x0b\x32 .com.seed.documents.v1alpha.Link\"\x85\x01\n\x04Link\x12\x34\n\x06source\x18\x01 \x01(\x0b\x32$.com.seed.documents.v1alpha.LinkNode\x12\x34\n\x06target\x18\x02 \x01(\x0b\x32$.com.seed.documents.v1alpha.LinkNode\x12\x11\n\tis_latest\x18\x03 \x01(\x08\"B\n\x08LinkNode\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x10\n\x08\x62lock_id\x18\x03 \x01(\t2\x84\x01\n\x0c\x43ontentGraph\x12t\n\rListCitations\x12\x30.com.seed.documents.v1alpha.ListCitationsRequest\x1a\x31.com.seed.documents.v1alpha.ListCitationsResponseB3Z1seed/backend/genproto/documents/v1alpha;documentsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'documents.v1alpha.content_graph_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1seed/backend/genproto/documents/v1alpha;documents'
  _LISTCITATIONSREQUEST._serialized_start=69
  _LISTCITATIONSREQUEST._serialized_end=112
  _LISTCITATIONSRESPONSE._serialized_start=114
  _LISTCITATIONSRESPONSE._serialized_end=186
  _LINK._serialized_start=189
  _LINK._serialized_end=322
  _LINKNODE._serialized_start=324
  _LINKNODE._serialized_end=390
  _CONTENTGRAPH._serialized_start=393
  _CONTENTGRAPH._serialized_end=525
# @@protoc_insertion_point(module_scope)
