# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from p2p.v1alpha import syncing_pb2 as p2p_dot_v1alpha_dot_syncing__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in p2p/v1alpha/syncing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SyncingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReconcileBlobs = channel.unary_unary(
                '/com.seed.p2p.v1alpha.Syncing/ReconcileBlobs',
                request_serializer=p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsRequest.SerializeToString,
                response_deserializer=p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsResponse.FromString,
                _registered_method=True)
        self.AnnounceBlobs = channel.unary_stream(
                '/com.seed.p2p.v1alpha.Syncing/AnnounceBlobs',
                request_serializer=p2p_dot_v1alpha_dot_syncing__pb2.AnnounceBlobsRequest.SerializeToString,
                response_deserializer=p2p_dot_v1alpha_dot_syncing__pb2.AnnounceBlobsProgress.FromString,
                _registered_method=True)


class SyncingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReconcileBlobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceBlobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReconcileBlobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileBlobs,
                    request_deserializer=p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsRequest.FromString,
                    response_serializer=p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsResponse.SerializeToString,
            ),
            'AnnounceBlobs': grpc.unary_stream_rpc_method_handler(
                    servicer.AnnounceBlobs,
                    request_deserializer=p2p_dot_v1alpha_dot_syncing__pb2.AnnounceBlobsRequest.FromString,
                    response_serializer=p2p_dot_v1alpha_dot_syncing__pb2.AnnounceBlobsProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.seed.p2p.v1alpha.Syncing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.seed.p2p.v1alpha.Syncing', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Syncing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReconcileBlobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.seed.p2p.v1alpha.Syncing/ReconcileBlobs',
            p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsRequest.SerializeToString,
            p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnounceBlobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.seed.p2p.v1alpha.Syncing/AnnounceBlobs',
            p2p_dot_v1alpha_dot_syncing__pb2.AnnounceBlobsRequest.SerializeToString,
            p2p_dot_v1alpha_dot_syncing__pb2.AnnounceBlobsProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
