# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p2p/v1alpha/syncing.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19p2p/v1alpha/syncing.proto\x12\x14\x63om.seed.p2p.v1alpha\"\x84\x01\n\x15ReconcileBlobsRequest\x12-\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\x1c.com.seed.p2p.v1alpha.Filter\x12<\n\x06ranges\x18\x02 \x03(\x0b\x32,.com.seed.p2p.v1alpha.SetReconciliationRange\"V\n\x16ReconcileBlobsResponse\x12<\n\x06ranges\x18\x01 \x03(\x0b\x32,.com.seed.p2p.v1alpha.SetReconciliationRange\"-\n\x06\x46ilter\x12\x10\n\x08resource\x18\x01 \x01(\t\x12\x11\n\trecursive\x18\x02 \x01(\x08\"\xd9\x01\n\x16SetReconciliationRange\x12?\n\x04mode\x18\x01 \x01(\x0e\x32\x31.com.seed.p2p.v1alpha.SetReconciliationRange.Mode\x12\x17\n\x0f\x62ound_timestamp\x18\x02 \x01(\x03\x12\x13\n\x0b\x62ound_value\x18\x03 \x01(\x0c\x12\x0e\n\x06values\x18\x04 \x03(\x0c\x12\x13\n\x0b\x66ingerprint\x18\x05 \x01(\x0c\"+\n\x04Mode\x12\x08\n\x04SKIP\x10\x00\x12\x0f\n\x0b\x46INGERPRINT\x10\x01\x12\x08\n\x04LIST\x10\x02\x32v\n\x07Syncing\x12k\n\x0eReconcileBlobs\x12+.com.seed.p2p.v1alpha.ReconcileBlobsRequest\x1a,.com.seed.p2p.v1alpha.ReconcileBlobsResponseB\'Z%seed/backend/genproto/p2p/v1alpha;p2pb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p.v1alpha.syncing_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z%seed/backend/genproto/p2p/v1alpha;p2p'
  _RECONCILEBLOBSREQUEST._serialized_start=52
  _RECONCILEBLOBSREQUEST._serialized_end=184
  _RECONCILEBLOBSRESPONSE._serialized_start=186
  _RECONCILEBLOBSRESPONSE._serialized_end=272
  _FILTER._serialized_start=274
  _FILTER._serialized_end=319
  _SETRECONCILIATIONRANGE._serialized_start=322
  _SETRECONCILIATIONRANGE._serialized_end=539
  _SETRECONCILIATIONRANGE_MODE._serialized_start=496
  _SETRECONCILIATIONRANGE_MODE._serialized_end=539
  _SYNCING._serialized_start=541
  _SYNCING._serialized_end=659
# @@protoc_insertion_point(module_scope)
