# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from p2p.v1alpha import syncing_pb2 as p2p_dot_v1alpha_dot_syncing__pb2


class SyncingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReconcileBlobs = channel.unary_unary(
                '/com.seed.p2p.v1alpha.Syncing/ReconcileBlobs',
                request_serializer=p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsRequest.SerializeToString,
                response_deserializer=p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsResponse.FromString,
                )


class SyncingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReconcileBlobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReconcileBlobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileBlobs,
                    request_deserializer=p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsRequest.FromString,
                    response_serializer=p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.seed.p2p.v1alpha.Syncing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Syncing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReconcileBlobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.seed.p2p.v1alpha.Syncing/ReconcileBlobs',
            p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsRequest.SerializeToString,
            p2p_dot_v1alpha_dot_syncing__pb2.ReconcileBlobsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
